Update SQL output module to current data model
steko/totalopenstation pull request #102
Opened 2019-09-08 20:25 UTC by steko

Fixes #101

2019-09-09 18:44 UTC, steko commented
Uhm, perhaps it's easier to fix this entire set of related bugs in one pull request...

2019-09-12 09:18 UTC, psolyca requested changes
Maybe you could change all Copyright year to be homogeneous.

2019-09-16 14:33 UTC, steko commented on totalopenstation/output/tops_sql.py
> +    y = point.geometry.y
I'm finding some documentation where the syntax is described as `POINT Z (1.0 2.0 3.0)`. Would you like this fix included in this PR @psolyca?

2019-09-16 16:18 UTC, psolyca commented on totalopenstation/output/tops_sql.py
> +    y = point.geometry.y
Yes, we could add it here.

2019-10-07 12:34 UTC, merged