add topcon model connector
steko/totalopenstation pull request #150
Opened 2021-09-15 12:20 UTC by enzococca

2021-09-15 12:50 UTC, steko requested changes
A few minor changes are needed.

2021-09-15 12:50 UTC, steko commented on totalopenstation/models/topcon.py
> +
These lines should be changed to reflect the filename and the author

2021-09-15 12:50 UTC, steko commented on totalopenstation/models/topcon.py
> +        Connector.__init__(self, port=port, baudrate=9600 , bytesize=8)
Do these settings apply for all TOPCON models? If they're tested on a specific device model we'd rather err on the side of caution and define it more narrowly.

2021-09-15 12:50 UTC, steko commented on totalopenstation/models/__init__.py
> +    'topcon': ('topcon', 'ModelConnector', 'TOPCON'),
According to their official website the capitalization is "Topcon"

2021-09-16 07:17 UTC, steko commented on totalopenstation/models/topcon_gpt_3005.py
> +# Copyright 2008 Enzo Cocca <enzo.ccc@gmail.com>
It's 2021 😉

2021-09-17 06:17 UTC, enzococca commented on totalopenstation/models/topcon_gpt_3005.py
> +# Copyright 2008 Enzo Cocca <enzo.ccc@gmail.com>
done

2021-09-17 13:46 UTC, steko commented
All looks good now, I don't understand why one of the travis checks is not working. Any idea @psolyca ?

2021-09-17 13:48 UTC, steko approved these changes

2021-09-17 13:49 UTC, steko approved these changes

2021-09-18 05:53 UTC, merged

2021-09-18 07:13 UTC, psolyca commented
> All looks good now, I don't understand why one of the travis checks is not working. Any idea @psolyca ?

@steko No idea, I have seen the message but did not had time to check why.

2021-09-18 07:53 UTC, steko commented
I fixed the Travis issue in the meantime, it was a leftover from the old settings. Now there is one check only (since it was basically a duplicate check).

Il 18 settembre 2021 09:13:24 CEST, Damien Gaignon ***@***.***> ha scritto:
>> All looks good now, I don't understand why one of the travis checks is not working. Any idea @psolyca ?
>
***@***.*** No idea, I have seen the message but did not had time to check why.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/totalopenstation/totalopenstation/pull/150#issuecomment-922230796