Nikon RAW fix issue #61
steko/totalopenstation pull request #67
Opened 2016-09-21 13:05 UTC by psolyca

Hey,

It is a fix for issue #61 as it is not in the enhanced parser PR.

2016-09-21 17:05 UTC, steko requested changes
I don't like the duplication of such a large block of code. Can we change it so both methods reuse a single function/set of functions?

2016-09-22 06:57 UTC, psolyca commented
I am not sure it is feasible.
Blocks are slightly different (at  the end) and use lots of class attributs.
I tried to write a function but I need to change all class attributs with instance attributs. Futhermore, there are 10 return variables and the function need 4 variables.

2016-09-27 07:14 UTC, steko approved these changes

2016-09-27 13:53 UTC, merged

2016-09-27 13:53 UTC, steko commented
Ok, I will work on a more streamlined version after merging your work. Thanks!